Workaround strange error from closure compiler.
axiom\fs\js\file_system.test.js:32: ERROR - actual parameter 1 of JsFileSystem$$module$axiom$fs$js$file_system.prototype.stat does not match formal parameter
found   : Path$$module$axiom$fs$path
required: string
      fs.stat(new Path('')).then(function (rv) {
              ^